language: go
sudo: false
dist: trusty

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.x
  - master

notifications:
  email: false

before_script:
  - curl https://glide.sh/get | sh

script:
  - glide install
  - go build
  - go test